laravel/routes/web.php
<?php

Route::get('/', function () {
return Redirect::to('/admin');
});

//Login Admin
Route::get('/admin',array('as' => 'admin.login','uses' => 'AdminController@getLogin'));
Route::post('/admin', array('as' => 'admin.auth.login','uses' => 'AdminController@postLogin'));

//Login Manager
//Route::get('/manager',array('as' => 'manager.login','uses' => 'ManagerController@getLogin'));
//Route::post('/manager', array('as' => 'manager.auth.login','uses' => 'ManagerController@postLogin'));

//Reset Password
Route::get('/resetpassword',array('as' => 'admin.autentikasi','uses' => 'AdminController@autentikasi'));
Route::post('/resetpassword/auth',array('as' => 'admin.reset.password','uses' => 'AdminController@sendEmailReminder'));

//REST API
Route::group(array('prefix'=>'api'),function(){
  Route::resource('webService','WebServiceController',array('except'=>array('create','edit')));
});

//Register
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//AJAX
Route::get('/ajax-call', function(){
  $id = Input::get('kd_outlet');
  $user = \App\Outlet::where('kd_outlet', '=', $id)
  ->join('user','outlet.kd_user','=','user.id')
  ->get();
  return Response::json($user);
});

Route::get('/ajax-city', function(){
  $id = Input::get('id');
  $city = \App\Kota::where('kd_area','=',$id)
  ->get();
  return Response::json($city);
});

Route::get('/ajax-area', function(){
  $id = Input::get('id');
  $area = \App\Area::where('id','=',$id)
  ->get();
  return Response::json($area);
});

Route::get('/ajax-sales', function(){
  $id = Input::get('id');
  $area = \App\User::where('kd_area','=',$id)
  ->where('kd_role','=','3')
  ->get();
  return Response::json($area);
});

// Route::group(['middlewareGroups' => ['web']], function () {
  Route::group(['middleware' => ['auth','admin','acl']], function()
  {
    // for debugging
    Route::get('outlet', array('as'=> 'outlet','uses' => 'MasterController@checking'));

    //Dashboard
    Route::get('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));
    Route::post('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));

    //ChangesPassword
    Route::get('/admin/changepassword',array('as' => 'admin.getChangePassword', 'uses' => 'AdminController@getChangePassword'));
    Route::post('/admin/changepassword',array('as' => 'admin.postChangePassword', 'uses' => 'AdminController@postChangePassword'));

    //Logout
    Route::get('admin/logout',array('as' => 'admin.logout','uses' =>'AdminController@getLogout'));

    //Sales Force
    Route::get('/admin/sales/{id}/delete',array('as'=> 'admin.sales.delete','uses' => 'SalesController@destroy'));
    Route::resource('/admin/sales', 'SalesController', ['as' => 'admin'] );

    //News
    Route::get('/admin/news/{id}/delete',array('as'=> 'admin.news.delete','uses' => 'NewsController@destroy'));
    Route::resource('/admin/news', 'NewsController', ['as' => "admin"] );

    //Banner
    Route::resource('/admin/banner', 'BannerController', ['as' => 'admin']);
    Route::get('/admin/banner/{id}/delete',array('as'=> 'admin.banner.delete','uses' => 'BannerController@destroy'));
    Route::get('/admin/banner/{id}/up',array('as'=> 'admin.banner.up','uses' => 'BannerController@up'));

    //User
    Route::get('/admin/user/{id}/delete',array('as'=> 'admin.user.delete','uses' => 'UserController@destroy'));
    Route::resource('/admin/user', 'UserController', ['as' => 'admin']);

    Route::get('/admin/master', array('as' => 'admin.master', 'uses' => 'MasterController@getMaster'));

    //Area
    Route::get('/admin/divisi/{id}/delete',array('as'=> 'admin.divisi.delete','uses' => 'AreaController@destroy'));
    Route::resource('/admin/divisi', 'AreaController', ['as' => 'admin']);

    //Kota
    Route::get('/admin/kota/{id}/delete',array('as'=> 'admin.kota.delete','uses' => 'KotaController@destroy'));
    Route::resource('/admin/kota', 'KotaController', ['as' => 'admin']);

    //Produk
    Route::get('/admin/produk/history/all', array('as'=> 'admin.produk.historyIndex','uses' => 'ProdukController@historyIndex'));
    Route::get('/admin/produk/history/{id}', array('as'=> 'admin.produk.history','uses' => 'ProdukController@ahistory'));

    Route::get('/admin/produk/{id}/delete',array('as'=> 'admin.produk.delete','uses' => 'ProdukController@destroy'));
    Route::resource('/admin/produk', 'ProdukController', ['as' => 'admin']);

    //Distributor
    Route::get('/admin/distributor/{id}/delete',array('as'=> 'admin.distributor.delete','uses' => 'DistributorController@destroy'));
    Route::resource('/admin/distributor', 'DistributorController', ['as' => 'admin']);

    Route::post('/ajax/outlet', array('as'=> 'admin.outlet.ajax','uses' => 'OutletController@ajax'));

    //Map
    Route::get('/admin/maps/view', array('as' => 'admin.outlet.mapform','uses' => 'OutletController@formMap'));

    //Map API
    Route::get('/admin/maps', array('as' => 'admin.outlet.maps','uses' => 'OutletController@maps'));


    //Toleransi Koordinat
    Route::get('admin/outletManage', array('as' => 'admin.outletManage.index','uses' => 'OutletController@formToleransi'));
    Route::post('admin/outletManage', array('as' => 'admin.outletManage.updateToleransi','uses' => 'OutletController@updateToleransi'));
    Route::post('admin/updateTvisit', array('as' => 'admin.outletManage.updateTvisit','uses' => 'OutletController@updateTvisit'));
    Route::post('admin/updateTec', array('as' => 'admin.outletManage.updateTec','uses' => 'OutletController@updateTec'));

    //Tipe Outlet
    Route::get('/admin/tipe/{id}/delete',array('as'=> 'admin.tipe.delete','uses' => 'TipeOutletController@destroy'));
    Route::resource('/admin/tipe', 'TipeOutletController', ['as' => 'admin']);

    //Visit Plan Get data
    Route::get('admin/visitPlan', array('as' => 'admin.visitPlan.form', 'uses' => 'VisitPlanController@formVisit'));
    Route::post('admin/visitPlan', array('as' => 'admin.visitPlan.result','uses' => 'VisitPlanController@index'));

    //Visit Bukti
     Route::get('/admin/visitbukti', array('as' => 'admin.visitbukti.form','uses' =>'VisitBuktiController@formbukti'));
     Route::post('admin/visitbukti', array('as' => 'admin.visitbukti.result','uses' => 'VisitBuktiController@index'));
      Route::get('admin/download/visitbukti',array('as' => 'admin.download.visitbukti','uses' =>'DownloadController@exportVisitBukti'));
     Route::get('/admin/visitbukti/{id}/delete',array('as'=> 'admin.visitbukti.delete','uses' => 'VisitBuktiController@destroy'));

     //Billing
    //Visit Monitor Get data
    Route::get('admin/billing', array('as' => 'admin.billing.form', 'uses' => 'BillingController@formBilling'));
    Route::post('admin/billing', array('as' => 'admin.billing.result','uses' => 'BillingController@index'));
     Route::get('/admin/billing/{id}/delete',array('as'=> 'admin.billing.delete','uses' => 'BillingController@destroy'));

      //Satuan
    Route::get('/admin/satuan/{id}/delete',array('as'=> 'admin.satuan.delete','uses' => 'SatuanController@destroy'));
    Route::resource('/admin/satuan', 'SatuanController', ['as' => "admin"] );

      //brand
    Route::get('/admin/brand/{id}/delete',array('as'=> 'admin.brand.delete','uses' => 'BrandController@destroy'));
    Route::resource('/admin/brand', 'BrandController', ['as' => "admin"] );

    //Approval Checklist
    Route::get('/admin/visit/approved',array('as'=> 'admin.visit.editApprove','uses' => 'VisitPlanController@editApprove'));
    Route::post('/admin/visit/approved',array('as'=> 'admin.visit.approved','uses' => 'VisitPlanController@approvedVisit'));
    Route::get('/admin/visit/approvedHO',array('as'=> 'admin.visit.approvedHO','uses' => 'VisitPlanController@editApproveHO'));

    //Visit Monitor Get data
    Route::get('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.form', 'uses' => 'VisitMonitorController@formVisit'));
    Route::post('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.result','uses' => 'VisitMonitorController@index'));

    //Visit Plan
    Route::get('/admin/visit/{id}/delete',array('as'=> 'admin.visit.delete','uses' => 'VisitPlanController@destroy'));
    Route::resource('/admin/visit', 'VisitPlanController', ['as' => 'admin']);

    //Visiting Monitor
    Route::get('/admin/visitMonitor/{id}/delete',array('as'=> 'admin.visitMonitor.delete','uses' => 'VisitMonitorController@destroy'));
    Route::resource('/admin/visitMonitor', 'VisitMonitorController', ['as' => 'admin']);

    //Visit Problem
    Route::resource('/admin/visitProblem', 'VisitProblemController');
    Route::get('/admin/visitProblem/{id}/delete',array('as'=> 'admin.visitProblem.delete','uses' => 'VisitProblemController@destroy'));
    Route::post('admin/visitProblem',  array('as' => 'admin.visitProblem.result', 'uses'=>'VisitProblemController@index' ));
    Route::get('admin/visitProblem', array('as'=> 'admin.visitProblem.form', 'uses'=> 'VisitProblemController@form'));

    //Approval VisitProblem
    Route::get('/admin/visitProblem/approving/yet',array('as'=> 'admin.visitProblem.editApprove','uses' => 'VisitProblemController@formapproval'));
    Route::post('/admin/visitProblem/approving',array('as'=> 'admin.visitProblem.approved','uses' => 'VisitProblemController@approvedProblem'));

    //Outlet
    Route::resource('/admin/outlet', 'OutletController', [ 'as' => 'admin']);
    Route::get('/admin/outlet/{kd_outlet}/delete',array('as'=> 'admin.outlet.delete','uses' => 'OutletController@destroy'));
    // Route::get('admin/outlet', array('as' => 'admin.outlet.index', 'uses'=> 'OutletController@formOutlet'));

   

    //Sampling
    Route::resource('/admin/sampling', 'SamplingController', ['as' => 'admin']);
    Route::get('/admin/sampling/{id}/delete',array('as'=> 'admin.sampling.delete','uses' => 'SamplingController@destroy'));

laravel/app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'news';
    protected $guarded = ['id'];
    public $timestamps = false;

    
}

laravel/app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Input;
use File;
use Auth;
use Session;
use Image;
use App\News;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class NewsController extends Controller
{
    public function index()
    {
        $data = News::orderBy('date_upload', 'desc')->get();
        return view('pages.news.index', compact('data'));
    }

    public function create()
    {
    	
        return view('pages.news.create');
    }


    public function store(Request $request)
    {
    	$filename='';
        if(Input::hasFile('path_image')){
            
            $file = $request->file('path_image');
            $destinationPath = 'image_upload/news/';
            $filename = str_random(6).'_'.$file->getClientOriginalName();
            $img = Image::make($file)->resize(600, null, function($constraint){
                $constraint->aspectRatio();
            })->encode('png')->save($destinationPath.$filename);
            
            
        }
        $news = new News();
        $news->judul = $request->input('judul');
        $news->headline = $request->input('headline');
        $news->content = $request->input('content');
        $news->path_image = $filename;
        $news->date_upload = date('Y-m-d H:i:s');
        $news->status = $request->input('status');

        $news->save();	
        
        $data['tipe']='News';
        $data['status']='new';
        $data['message']=json_encode($news);  
        
        $log = new AdminController;
        $log->getLogHistory('Add News');
        $this->sendNotif($data);
        //echo 'berhasil';
        return redirect()->route('admin.news.index');
    }

    public function edit($id)
    {
        $data['content'] = News::find($id);

        
        return view('pages.news.edit')->with('data',$data);
    }

    public function update(Request $request, $id)
    {
        $news = News::find($id);
        $news->update($request->all()); 
        
        if(Input::hasFile('path_image')){
         File::delete('image_upload/news/'.$news->path_image);    
            $file = $request->file('path_image');
            $destinationPath = 'image_upload/news/';
            $filename = str_random(6).'_'.$file->getClientOriginalName();
            $img = Image::make($file)->resize(600, null, function($constraint){
                $constraint->aspectRatio();
            })->encode('png')->save($destinationPath.$filename);
            $news->path_image=$filename;
            $news->save();
        }
        $log = new AdminController;
        $log->getLogHistory('Update News with ID '.$id);

        return redirect()->route('admin.news.index');
    }

    public function sendNotif($data){
        $ch = curl_init("https://fcm.googleapis.com/fcm/send");
        $header = array
        (
            'Authorization: key=AAAA_xS6-L0:APA91bEYaR-O3xM8FvcFqo6BOuOWNHaYId6Th0KExWi9dHfWlGWLAfnsUaQpLaVrZKqKIjWZD2ExvfxlOf2gZlPPA0msaGcilVik5mYEOA95TDriQ7plaZwZkes7-3tm4fWHJNINdr4W',
            'Content-Type: application/json'
        );
        $msg = array
        (
            'to'        => "/topics/allDevices",
            'priority'      => "high",
            'data'  => $data
        );
        curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
        curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
        curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS,json_encode($msg));

        $response = curl_exec($ch);
        //echo 'a';
        //print_r($data);
        print_r($response);
        curl_close($ch);
    }

    public function destroy($id)
    {
        $data = News::find($id);
        $id = $data->id;
        $data->delete();
        $dataa['tipe']='News';
        $dataa['status']='reject';
        $dataa['message']=json_encode(array('id'=>$id));  
        $this->sendNotif($dataa);
        $log = new AdminController;
        $log->getLogHistory('Delete News with ID '.$id);
        return redirect()->route('admin.news.index'); 
    }

}

laravel/resources/views/pages/news/create.blade.php
@extends('layouts.master')

@section('link', '
    <link href="/doodle/vendors/bower_components/dropify/dist/css/dropify.min.css" rel="stylesheet" type="text/css"/>')

@section('title', 'Create Article')

@section('content')


		<!-- Main Content -->
		<div class="page-wrapper">
            <div class="container-fluid">
				
				<!-- Title -->
				<div class="row heading-bg">
					<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
						<h5 class="txt-dark">article management</h5>
					</div>
					<!-- Breadcrumb -->
					<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
						<ol class="breadcrumb">
							<li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
							<li><a href="#"><span>Master Data</span></a></li>
							<li><a href="{{url('/admin/article')}}"><span>Article</span></a></li>
							<li class="active"><span>Add Article</span></li>
						</ol>
					</div>
					<!-- /Breadcrumb -->
				</div>
				<!-- /Title -->

				<!-- Row -->
					<div class="row">
						<div class="col-md-12">
							<div class="panel panel-warning card-view">
								<div class="panel-heading">
									<div class="pull-left">
										<h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Form Add Article</h6>
									</div>
									@include('partials.panel')
									<div class="clearfix"></div>
								</div>
								<div id="collapse_1" class="panel-wrapper collapse in">
									<div class="panel-body">
										<div class="row">
											<div class="col-md-12">
												<div class="form-wrap">
													{!! Form::open(array('route' => 'admin.article.store', 'method' => 'POST', 'files' => true, 'data-toggle' => 'validator', 'role' => 'form')) !!}
														@include('pages.article.form',array('submit' => 'Simpan'))
													{!! Form::close() !!}
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<!-- /Row -->

				@include('partials.footer')

			</div>
		</div>
        <!-- /Main Content -->

@endsection

@section('script', '
    <!-- Bootstrap Dropify JavaScript -->
    <script src="/doodle/vendors/bower_components/dropify/dist/js/dropify.min.js"></script>
    <!-- Form File Upload Data JavaScript -->
    <script src="/doodle/dist/js/form-file-upload-data.js"></script>')

laravel/resources/views/pages/news/edit.blade.php
@extends('layouts.master')

@section('link', '
    <link href="/doodle/vendors/bower_components/dropify/dist/css/dropify.min.css" rel="stylesheet" type="text/css"/>')

@section('title', 'Edit Article')

@section('content')


		<!-- Main Content -->
		<div class="page-wrapper">
            <div class="container-fluid">
				
				<!-- Title -->
				<div class="row heading-bg">
					<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
						<h5 class="txt-dark">article management</h5>
					</div>
					<!-- Breadcrumb -->
					<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
						<ol class="breadcrumb">
							<li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
							<li><a href="#"><span>Master Data</span></a></li>
							<li><a href="{{url('/admin/article')}}"><span>Article</span></a></li>
							<li class="active"><span>Edit Article</span></li>
						</ol>
					</div>
					<!-- /Breadcrumb -->
				</div>
				<!-- /Title -->

				<!-- Row -->
					<div class="row">
						<div class="col-md-12">
							<div class="panel panel-warning card-view">
								<div class="panel-heading">
									<div class="pull-left">
										<h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Form Edit Article</h6>
									</div>
									@include('partials.panel')
									<div class="clearfix"></div>
								</div>
								<div id="collapse_1" class="panel-wrapper collapse in">
									<div class="panel-body">
										<div class="row">
											<div class="col-md-12">
												<div class="form-wrap">
													{!! Form::model($data['content'],array('route' => ['admin.news.update',$data['content']->id], 'method' => 'PUT', 'data-toggle' => 'validator', 'role' => 'form', 'files' => true)) !!}
														 @include('pages.news.form-edit',array('submit' => 'Perbarui'))
													{!! Form::close() !!}
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<!-- /Row -->

				@include('partials.footer')

			</div>
		</div>
        <!-- /Main Content -->

@endsection

@section('script', '
    <!-- Bootstrap Dropify JavaScript -->
    <script src="/doodle/vendors/bower_components/dropify/dist/js/dropify.min.js"></script>
    <!-- Form File Upload Data JavaScript -->
    <script src="/doodle/dist/js/form-file-upload-data.js"></script>')

laravel/resources/views/pages/news/form-edit.blade.php
<div class="col-xs-6 col-sm-4 col-sm-offset-4">
	<div class="form-group">
		{!! Form::label('judul','Judul', array('class' => 'control-label mb-10')) !!}
		{!! Form::text('judul',null, array('class' => 'form-control', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('headline','Headline', array('class' => 'control-label mb-10')) !!}
		{!! Form::text('headline',null, array('class' => 'form-control', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('content','Isi Berita', array('class' => 'control-label mb-10')) !!}
		{!! Form::textarea('content',null, array('rows'=>'5', 'class' => 'form-control', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('path_image','Upload Picture', array('class' => 'control-label mb-10')) !!}
		<input type="file" id="input-file-now" name="path_image" class="dropify" data-height="206" data-default-file="{{ asset('/image_upload/article/'.$data['content']->path_image) }}"/>
	</div>
	<div class="form-group">
		{!! Form::label('status','Status', array('class' => 'control-label mb-10')) !!}
		{!! Form::select('status', [
		   '1' => 'Enable',
		   '0' => 'Disable',
		], null, array('class' => 'selectpicker', 'data-style' => 'form-control btn-default btn-outline')) !!} 
	</div>
	@include('partials.errors')
	<div class="form-group mb-0">
		{!! Form::submit($submit, array('class' => 'btn btn-primary btn-anim'))!!}
	</div>
</div>

<!-- Moment JavaScript -->
<script type="text/javascript" src="/doodle/vendors/bower_components/moment/min/moment-with-locales.min.js"></script>		

laravel/resources/views/pages/news/form.blade.php
<div class="col-xs-6 col-sm-4 col-sm-offset-4">
	<div class="form-group">
		{!! Form::label('judul','Judul', array('class' => 'control-label mb-10')) !!}
		{!! Form::text('judul',null, array('class' => 'form-control', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('headline','Headline', array('class' => 'control-label mb-10')) !!}
		{!! Form::text('headline',null, array('class' => 'form-control', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('content','Isi Berita', array('class' => 'control-label mb-10')) !!}
		{!! Form::textarea('content',null, array('rows'=>'5', 'class' => 'form-control', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('path_image','Upload Picture', array('class' => 'control-label mb-10')) !!}
		<input type="file" id="input-file-now" name="path_image" class="dropify" data-height="206"/>
	</div>
	<div class="form-group">
		{!! Form::label('status','Status', array('class' => 'control-label mb-10')) !!}
		{!! Form::select('status', [
		   '1' => 'Enable',
		   '0' => 'Disable',
		], null, array('class' => 'selectpicker', 'data-style' => 'form-control btn-default btn-outline')) !!} 
	</div>
	@include('partials.errors')
	<div class="form-group mb-0">
		{!! Form::submit($submit, array('class' => 'btn btn-primary btn-anim'))!!}
	</div>
</div>

<!-- Moment JavaScript -->
<script type="text/javascript" src="/doodle/vendors/bower_components/moment/min/moment-with-locales.min.js"></script>		

laravel/resources/views/pages/news/index.blade.php
@extends('layouts.master')

@section('title', 'News List')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">News management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>News</span></a></li>
                            <li class="active"><span>List</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-warning card-view">
                            <div class="panel-heading">
                                <div class="pull-left">
                                    <h6 class="panel-title txt-light"><i class="fa fa-user"></i>&nbsp;&nbsp;News List</h6>
                                </div>

                                @include('partials.panel')

                                <div class="clearfix"></div>
                            </div>
                            <div id="collapse_1" class="panel-wrapper collapse in">
                                <div class="panel-body">
                                    <div class="table-wrap">
                                        
                                        @if(Auth::user()->hasAccess('admin.news.create'))  
                                            <a href="{!! route('admin.news.create') !!}" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah Article</a>
                                        @endif
                                     
                                        <div class="table-responsive">
                                            <table class="table datable_1 table-hover table-bordered display mb-30">
                                                <thead>
                                                    <tr>
                                                        <th style="text-align:center;">No</th>
                                                        <th style="text-align:center;">Judul</th>
                                                        <th style="text-align:center;">Headline</th>
                                                        <th style="text-align:center;">Content</th>
                                                        <th style="text-align:center;">Thumbnail</th>
                                                        <th style="text-align:center;">Date Upload</th>
                                                        <th style="text-align:center;">Status</th>
                                                        @if(Auth::user()->kd_role != 3)
                                                            <th style="min-width:108px">Action</th>
                                                        @endif
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($data as $key => $row)
                                                        <tr>
                                                        	<td><center>{{ $key+1 }}</center></td>
                                                            <td><center>{{ $row->judul }}</center></td>
                                                            <td><center>{{ $row->headline }}</center></td>
                                                            <td><center>{{  substr($row->content, 0, 200) }}</center></td>
                                                        	@if(File::exists('image_upload/news/'.$row->path_image) and $row->path_image != '')
							                                    <td><center><a href="{!! url('image_upload/news/'.$row->path_image) !!}" target="_blank" >
							                                        <img style="max-height: 120px; max-width: 120px;" src="{!! url('image_upload/news/'.$row->path_image) !!}" class="img-responsive" /></a>
							                                    </center></td>
							                                @else
							                                    <td><center><img style="max-height: 120px; max-width: 120px;" src="{!! url('/img/no_image_outlet_upload.png') !!}" class="img-responsive" /></center></td>
							                                @endif 
                                                               
							                                <td style="min-width:75px">
                                                                <center>{{ $row->date_upload }}</center>
                                                            </td>
							                               
							                                @if($row->status == 1)
                                                                <td>
                                                                    <center><span class="label label-success">Enabled</span></center>
                                                                </td>
                                                            @elseif($row->status == 0)
                                                                <td>
                                                                    <center><span class="label label-warning">Disabled</span></center>
                                                                </td>
                                                            @endif
                                                            
                                                            
                                                                <td >
                                                                        @if(Auth::user()->kd_role != 3)
                                                                       <div class="button-list">
                                                                            <a href="{!! route('admin.news.edit',[$row->id]) !!}" data-toggle="tooltip" title="Edit" class="btn btn-primary btn-sm btn-icon-anim btn-square mr-5" style="display: unset;"><i class="fa fa-pencil" style="font-size: 14px;"></i></a>

                                                                            <a href="{!! route('admin.news.delete',[$row->id]) !!}" id="delete" data-toggle="tooltip" title="Delete" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger btn-sm btn-icon-anim btn-square mr-5" style="display: unset;"><i class="fa fa-trash" style="font-size: 14px;"></i></a>
                                                                            
                                                                        </div>
                                                                         @endif
                                                                </td>
                                                           
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
                <!-- /Row -->
            
                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

        @include('partials.sweetalert')

        @push('message')
            @include('partials.toastr')
        @endpush
        
@endsection