laravel/routes/web.php
<?php

Route::get('/', function () {
return Redirect::to('/admin');
});

//Login Admin
Route::get('/admin',array('as' => 'admin.login','uses' => 'AdminController@getLogin'));
Route::post('/admin', array('as' => 'admin.auth.login','uses' => 'AdminController@postLogin'));

//Login Manager
//Route::get('/manager',array('as' => 'manager.login','uses' => 'ManagerController@getLogin'));
//Route::post('/manager', array('as' => 'manager.auth.login','uses' => 'ManagerController@postLogin'));

//Reset Password
Route::get('/resetpassword',array('as' => 'admin.autentikasi','uses' => 'AdminController@autentikasi'));
Route::post('/resetpassword/auth',array('as' => 'admin.reset.password','uses' => 'AdminController@sendEmailReminder'));

//REST API
Route::group(array('prefix'=>'api'),function(){
  Route::resource('webService','WebServiceController',array('except'=>array('create','edit')));
});

//Register
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//AJAX
Route::get('/ajax-call', function(){
  $id = Input::get('kd_outlet');
  $user = \App\Outlet::where('kd_outlet', '=', $id)
  ->join('user','outlet.kd_user','=','user.id')
  ->get();
  return Response::json($user);
});

Route::get('/ajax-city', function(){
  $id = Input::get('id');
  $city = \App\Kota::where('kd_area','=',$id)
  ->get();
  return Response::json($city);
});

Route::get('/ajax-area', function(){
  $id = Input::get('id');
  $area = \App\Area::where('id','=',$id)
  ->get();
  return Response::json($area);
});

Route::get('/ajax-sales', function(){
  $id = Input::get('id');
  $area = \App\User::where('kd_area','=',$id)
  ->where('kd_role','=','3')
  ->get();
  return Response::json($area);
});

// Route::group(['middlewareGroups' => ['web']], function () {
  Route::group(['middleware' => ['auth','admin','acl']], function()
  {
    // for debugging
    Route::get('outlet', array('as'=> 'outlet','uses' => 'MasterController@checking'));

    //Dashboard
    Route::get('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));
    Route::post('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));

    //ChangesPassword
    Route::get('/admin/changepassword',array('as' => 'admin.getChangePassword', 'uses' => 'AdminController@getChangePassword'));
    Route::post('/admin/changepassword',array('as' => 'admin.postChangePassword', 'uses' => 'AdminController@postChangePassword'));

    //Logout
    Route::get('admin/logout',array('as' => 'admin.logout','uses' =>'AdminController@getLogout'));

    //Sales Force
    Route::get('/admin/sales/{id}/delete',array('as'=> 'admin.sales.delete','uses' => 'SalesController@destroy'));
    Route::resource('/admin/sales', 'SalesController', ['as' => 'admin'] );

    //News
    Route::get('/admin/news/{id}/delete',array('as'=> 'admin.news.delete','uses' => 'NewsController@destroy'));
    Route::resource('/admin/news', 'NewsController', ['as' => "admin"] );

    //Banner
    Route::resource('/admin/banner', 'BannerController', ['as' => 'admin']);
    Route::get('/admin/banner/{id}/delete',array('as'=> 'admin.banner.delete','uses' => 'BannerController@destroy'));
    Route::get('/admin/banner/{id}/up',array('as'=> 'admin.banner.up','uses' => 'BannerController@up'));

    //User
    Route::get('/admin/user/{id}/delete',array('as'=> 'admin.user.delete','uses' => 'UserController@destroy'));
    Route::resource('/admin/user', 'UserController', ['as' => 'admin']);

    Route::get('/admin/master', array('as' => 'admin.master', 'uses' => 'MasterController@getMaster'));

    //Area
    Route::get('/admin/divisi/{id}/delete',array('as'=> 'admin.divisi.delete','uses' => 'AreaController@destroy'));
    Route::resource('/admin/divisi', 'AreaController', ['as' => 'admin']);

    //Kota
    Route::get('/admin/kota/{id}/delete',array('as'=> 'admin.kota.delete','uses' => 'KotaController@destroy'));
    Route::resource('/admin/kota', 'KotaController', ['as' => 'admin']);

    //Produk
    Route::get('/admin/produk/history/all', array('as'=> 'admin.produk.historyIndex','uses' => 'ProdukController@historyIndex'));
    Route::get('/admin/produk/history/{id}', array('as'=> 'admin.produk.history','uses' => 'ProdukController@ahistory'));

    Route::get('/admin/produk/{id}/delete',array('as'=> 'admin.produk.delete','uses' => 'ProdukController@destroy'));
    Route::resource('/admin/produk', 'ProdukController', ['as' => 'admin']);

    //Distributor
    Route::get('/admin/distributor/{id}/delete',array('as'=> 'admin.distributor.delete','uses' => 'DistributorController@destroy'));
    Route::resource('/admin/distributor', 'DistributorController', ['as' => 'admin']);

    Route::post('/ajax/outlet', array('as'=> 'admin.outlet.ajax','uses' => 'OutletController@ajax'));

    //Map
    Route::get('/admin/maps/view', array('as' => 'admin.outlet.mapform','uses' => 'OutletController@formMap'));

    //Map API
    Route::get('/admin/maps', array('as' => 'admin.outlet.maps','uses' => 'OutletController@maps'));


    //Toleransi Koordinat
    Route::get('admin/outletManage', array('as' => 'admin.outletManage.index','uses' => 'OutletController@formToleransi'));
    Route::post('admin/outletManage', array('as' => 'admin.outletManage.updateToleransi','uses' => 'OutletController@updateToleransi'));
    Route::post('admin/updateTvisit', array('as' => 'admin.outletManage.updateTvisit','uses' => 'OutletController@updateTvisit'));
    Route::post('admin/updateTec', array('as' => 'admin.outletManage.updateTec','uses' => 'OutletController@updateTec'));

    //Tipe Outlet
    Route::get('/admin/tipe/{id}/delete',array('as'=> 'admin.tipe.delete','uses' => 'TipeOutletController@destroy'));
    Route::resource('/admin/tipe', 'TipeOutletController', ['as' => 'admin']);

    //Visit Plan Get data
    Route::get('admin/visitPlan', array('as' => 'admin.visitPlan.form', 'uses' => 'VisitPlanController@formVisit'));
    Route::post('admin/visitPlan', array('as' => 'admin.visitPlan.result','uses' => 'VisitPlanController@index'));

    //Visit Bukti
     Route::get('/admin/visitbukti', array('as' => 'admin.visitbukti.form','uses' =>'VisitBuktiController@formbukti'));
     Route::post('admin/visitbukti', array('as' => 'admin.visitbukti.result','uses' => 'VisitBuktiController@index'));
      Route::get('admin/download/visitbukti',array('as' => 'admin.download.visitbukti','uses' =>'DownloadController@exportVisitBukti'));
     Route::get('/admin/visitbukti/{id}/delete',array('as'=> 'admin.visitbukti.delete','uses' => 'VisitBuktiController@destroy'));

     //Billing
    //Visit Monitor Get data
    Route::get('admin/billing', array('as' => 'admin.billing.form', 'uses' => 'BillingController@formBilling'));
    Route::post('admin/billing', array('as' => 'admin.billing.result','uses' => 'BillingController@index'));
     Route::get('/admin/billing/{id}/delete',array('as'=> 'admin.billing.delete','uses' => 'BillingController@destroy'));

      //Satuan
    Route::get('/admin/satuan/{id}/delete',array('as'=> 'admin.satuan.delete','uses' => 'SatuanController@destroy'));
    Route::resource('/admin/satuan', 'SatuanController', ['as' => "admin"] );

      //brand
    Route::get('/admin/brand/{id}/delete',array('as'=> 'admin.brand.delete','uses' => 'BrandController@destroy'));
    Route::resource('/admin/brand', 'BrandController', ['as' => "admin"] );

    //Approval Checklist
    Route::get('/admin/visit/approved',array('as'=> 'admin.visit.editApprove','uses' => 'VisitPlanController@editApprove'));
    Route::post('/admin/visit/approved',array('as'=> 'admin.visit.approved','uses' => 'VisitPlanController@approvedVisit'));
    Route::get('/admin/visit/approvedHO',array('as'=> 'admin.visit.approvedHO','uses' => 'VisitPlanController@editApproveHO'));

    //Visit Monitor Get data
    Route::get('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.form', 'uses' => 'VisitMonitorController@formVisit'));
    Route::post('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.result','uses' => 'VisitMonitorController@index'));

    //Visit Plan
    Route::get('/admin/visit/{id}/delete',array('as'=> 'admin.visit.delete','uses' => 'VisitPlanController@destroy'));
    Route::resource('/admin/visit', 'VisitPlanController', ['as' => 'admin']);

    //Visiting Monitor
    Route::get('/admin/visitMonitor/{id}/delete',array('as'=> 'admin.visitMonitor.delete','uses' => 'VisitMonitorController@destroy'));
    Route::resource('/admin/visitMonitor', 'VisitMonitorController', ['as' => 'admin']);

    //Visit Problem
    Route::resource('/admin/visitProblem', 'VisitProblemController');
    Route::get('/admin/visitProblem/{id}/delete',array('as'=> 'admin.visitProblem.delete','uses' => 'VisitProblemController@destroy'));
    Route::post('admin/visitProblem',  array('as' => 'admin.visitProblem.result', 'uses'=>'VisitProblemController@index' ));
    Route::get('admin/visitProblem', array('as'=> 'admin.visitProblem.form', 'uses'=> 'VisitProblemController@form'));

    //Approval VisitProblem
    Route::get('/admin/visitProblem/approving/yet',array('as'=> 'admin.visitProblem.editApprove','uses' => 'VisitProblemController@formapproval'));
    Route::post('/admin/visitProblem/approving',array('as'=> 'admin.visitProblem.approved','uses' => 'VisitProblemController@approvedProblem'));

    //Outlet
    Route::resource('/admin/outlet', 'OutletController', [ 'as' => 'admin']);
    Route::get('/admin/outlet/{kd_outlet}/delete',array('as'=> 'admin.outlet.delete','uses' => 'OutletController@destroy'));
    // Route::get('admin/outlet', array('as' => 'admin.outlet.index', 'uses'=> 'OutletController@formOutlet'));

   

    //Sampling
    Route::resource('/admin/sampling', 'SamplingController', ['as' => 'admin']);
    Route::get('/admin/sampling/{id}/delete',array('as'=> 'admin.sampling.delete','uses' => 'SamplingController@destroy'));

laravel/app/Kota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Area;

class Kota extends Model
{
    //
    protected $table = 'kota';
    protected $guarded = ['id'];
    public $timestamps = false;

    public function areas()
    {
    	return $this->belongsTo('App\Area', 'kd_area', 'id');
    }
}

laravel/app/Http/Controllers/KotaController.php
<?php
/*
PT. Trikarya Teknologi Indonesia
Tenggilis raya 127
Office Complex Apartment Metropolis MKB 206
Surabaya, Jawa timur, Indonesia
Phone : +6231-8420384 / +6281235537717
*/
namespace App\Http\Controllers;

use DB;
use Auth;
use Session;
use App\Area;
use App\Kota;
use App\Http\Controllers\Controller;
use App\Http\Requests\KotaRequest;
use App\Http\Controllers\AdminController;
use Illuminate\Http\Request;

class KotaController extends Controller
{
    public function index()
    {
        //$data['content'] = Area::all();
        $products = DB::table('area')->join('kota', 'kota.kd_area', '=', 'area.id')->get();
        return view('pages.area.index', compact('products'));
    }

    public function create()
    {
        $data['area'] = ['' => 'Select Area'] + Area::pluck('nm_area', 'id')->toArray();
        return view('pages.kota.create', compact('data'));
    }

    public function store(KotaRequest $request)
    {
        Kota::create($request->all());
        $log = new AdminController;
	$log->getLogHistory('Make New Kota');
        return redirect()->route('admin.area.index');
    }

    public function edit($id)
    {
        $data['content'] = Kota::find($id);
        $data['area'] = Area::pluck('nm_area', 'id')->toArray();
        return view('pages.kota.edit', compact('data'));
    }

    public function update(KotaRequest $request, $id)
    {
        $data = Kota::find($id);
        $data->update($request->all());
        $log = new AdminController;
	$log->getLogHistory('Update Kota with ID '.$id);
        return redirect()->route('admin.area.index');
    }

    public function destroy($id)
    {
        $data =Kota::find($id);
        $data->delete();
        $log = new AdminController;
	$log->getLogHistory('Delete Kota with ID '.$id);
        return redirect()->route('admin.area.index');
    }

    
}

laravel/resources/views/pages/kota/create.blade.php
@extends('layouts.master')

@section('title', 'Add Kota')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">kota management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Master Data</span></a></li>
                            <li><a href="{{url('/admin/kota')}}"><span>Kota</span></a></li>
                            <li class="active"><span>Add Kota</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-warning card-view">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Form Add Kota</h6>
                                    </div>
                                    @include('partials.panel')
                                    <div class="clearfix"></div>
                                </div>
                                <div id="collapse_1" class="panel-wrapper collapse in">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-wrap">

                                                    {!! Form::open(array('route' => 'admin.kota.store', 'method' => 'POST', 'data-toggle' => 'validator', 'role' => 'form')) !!}
												    @include('pages.kota.form',array('submit' => 'Simpan'))
												    {!! Form::close() !!}

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

@endsection

laravel/resources/views/pages/kota/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Kota')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">kota management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Master Data</span></a></li>
                            <li><a href="{{url('/admin/kota')}}"><span>Kota</span></a></li>
                            <li class="active"><span>Edit Kota</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-warning card-view">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Form Edit Kota</h6>
                                    </div>
                                    @include('partials.panel')
                                    <div class="clearfix"></div>
                                </div>
                                <div id="collapse_1" class="panel-wrapper collapse in">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-wrap">

                                                    {!! Form::model($data['content'],array('route' => ['admin.kota.update',$data['content']->id], 'method' => 'PUT', 'data-toggle' => 'validator', 'role' => 'form')) !!}
                                                        @include('pages.kota.form',array('submit' => 'Perbarui'))
                                                    {!! Form::close() !!}

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

@endsection

laravel/resources/views/pages/kota/form.blade.php
<div class="col-xs-6 col-sm-4 col-sm-offset-4">
	<div class="form-group">
		{!! Form::label('kd_area', 'Kode Area', array('class' => 'control-label mb-10')) !!}
	     {!! Form::select('kd_area', $data['area'], null, ['class'=> 'form-control', 'required'=>'required', 'disabled'=>'true'])!!}
	</div>
	<div class="form-group">
	    {!! Form::label('nm_area','Nama Area : ', array('class' => 'control-label mb-10')) !!}
	    <div id="namaArea" name="namaArea" class="control-label mb-10"></div>
	</div>
	<div class="form-group">
		{!! Form::label('nm_kota','Nama Kota', array('class' => 'control-label mb-10')) !!}
		{!! Form::text('nm_kota',null, array('class' => 'form-control', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::submit($submit, array('class' => 'btn btn-primary')) !!}
	</div>
</div>
	<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
	<script>
		$('#area').on('change', function(e) {
	        console.log(e);
	        var id = e.target.value;
	        //ajax
	        $.getJSON('{{url('/ajax-area?id=')}}'+id, function (data) {
				//console.log(data);
	            $('#namaArea').empty();
	          	$.each(data, function(index, areaObj){
	            	 $('#namaArea').append('<div><mark>'+areaObj.nm_area+'</mark></div>');
				});
	        });
	    });
	</script>

laravel/resources/views/pages/kota/index.blade.php
<!-- bootstrap 3.0.2 -->
{!! Html::style('css/bootstrap.min.css') !!}
<!-- font Awesome -->
{!! Html::style('css/font-awesome.min.css') !!} 
<!-- Ionicons -->
{!! Html::style('css/ionicons.min.css') !!}
<!-- bootstrap wysihtml5 - text editor -->
{!! Html::style('css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') !!}
<!-- Theme style -->
{!! Html::style('css/AdminLTE.css') !!}

{!! Html::style('css/skins/_all-skins.min.css') !!}
@section('content')
<div style="margin-left:30px;margin-right:30px;">
<section class="content-header">
        <h1>
            Dashboard
            <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{!! route('admin.dashboard') !!}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Area Lists &nbsp;&nbsp;&nbsp;
                            <br>
                            <a href="{!! route('admin.area.create') !!}" class="btn btn-primary">Tambah Area </a>
                            
                            <a href="{!! route('admin.kota.create') !!}" class="btn btn-primary">Tambah Kota </a>
                            </br>
                        </h3>                                    
                    </div>
                    <div class="box-body table-responsive">                                 
                        <table id="dataTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>&nbsp;</th>
                                    <th>Kode Area</th>
                                    <th>Nama Area</th>
                                    <th>Kode Kota</th>
                                    <th>Nama Kota</th>
                                    @if(Auth::user()->kd_role != 3)
                                        <th>Action</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($products as $row)
                                <tr>
                                    <td>&nbsp;</td>
                                    <td>{{ $row->kd_area }}</td>
                                    <td>{{ $row->nm_area }}</td>
                                    <td>{{ $row->id }}</td>
                                    <td>{{ $row->nm_kota }}</td>
                                    @if(Auth::user()->kd_role != 3)
                                        <td>                                   
                                        <a href="{!! route('admin.area.edit',[$row->id]) !!}" class="fa fa-pencil-square-o">Edit</a>
                                        <!--@if(Auth::user()->hasAccess('admin.user.delete'))-->
                                        <a href="javascript:void(0);" onclick="return confirm('Are you sure you want to delete this item?');" data-href="{!! route('admin.area.delete',[$row->id]) !!}" class="fa fa-trash-o"> 
                                        Delete
                                        </a>
                                        <!--@endif-->
                                        </td>
                                    @endif
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div>
        </div><!-- /.row (main row) -->
</section><!-- /.content -->
</div>
@include('scripts.delete-modal')
@endsection

@section('custom-head')
    {!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
    {!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
    {!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
    <script type="text/javascript">
        $(function() {
                $('#dataTable').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
    </script>
@endsection