laravel/routes/web.php
<?php

Route::get('/', function () {
return Redirect::to('/admin');
});

//Login Admin
Route::get('/admin',array('as' => 'admin.login','uses' => 'AdminController@getLogin'));
Route::post('/admin', array('as' => 'admin.auth.login','uses' => 'AdminController@postLogin'));

//Login Manager
//Route::get('/manager',array('as' => 'manager.login','uses' => 'ManagerController@getLogin'));
//Route::post('/manager', array('as' => 'manager.auth.login','uses' => 'ManagerController@postLogin'));

//Reset Password
Route::get('/resetpassword',array('as' => 'admin.autentikasi','uses' => 'AdminController@autentikasi'));
Route::post('/resetpassword/auth',array('as' => 'admin.reset.password','uses' => 'AdminController@sendEmailReminder'));

//REST API
Route::group(array('prefix'=>'api'),function(){
  Route::resource('webService','WebServiceController',array('except'=>array('create','edit')));
});

//Register
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//AJAX
Route::get('/ajax-call', function(){
  $id = Input::get('kd_outlet');
  $user = \App\Outlet::where('kd_outlet', '=', $id)
  ->join('user','outlet.kd_user','=','user.id')
  ->get();
  return Response::json($user);
});

Route::get('/ajax-city', function(){
  $id = Input::get('id');
  $city = \App\Kota::where('kd_area','=',$id)
  ->get();
  return Response::json($city);
});

Route::get('/ajax-area', function(){
  $id = Input::get('id');
  $area = \App\Area::where('id','=',$id)
  ->get();
  return Response::json($area);
});

Route::get('/ajax-sales', function(){
  $id = Input::get('id');
  $area = \App\User::where('kd_area','=',$id)
  ->where('kd_role','=','3')
  ->get();
  return Response::json($area);
});

// Route::group(['middlewareGroups' => ['web']], function () {
  Route::group(['middleware' => ['auth','admin','acl']], function()
  {
    // for debugging
    Route::get('outlet', array('as'=> 'outlet','uses' => 'MasterController@checking'));

    //Dashboard
    Route::get('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));
    Route::post('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));

    //ChangesPassword
    Route::get('/admin/changepassword',array('as' => 'admin.getChangePassword', 'uses' => 'AdminController@getChangePassword'));
    Route::post('/admin/changepassword',array('as' => 'admin.postChangePassword', 'uses' => 'AdminController@postChangePassword'));

    //Logout
    Route::get('admin/logout',array('as' => 'admin.logout','uses' =>'AdminController@getLogout'));

    //Sales Force
    Route::get('/admin/sales/{id}/delete',array('as'=> 'admin.sales.delete','uses' => 'SalesController@destroy'));
    Route::resource('/admin/sales', 'SalesController', ['as' => 'admin'] );

    //News
    Route::get('/admin/news/{id}/delete',array('as'=> 'admin.news.delete','uses' => 'NewsController@destroy'));
    Route::resource('/admin/news', 'NewsController', ['as' => "admin"] );

    //Banner
    Route::resource('/admin/banner', 'BannerController', ['as' => 'admin']);
    Route::get('/admin/banner/{id}/delete',array('as'=> 'admin.banner.delete','uses' => 'BannerController@destroy'));
    Route::get('/admin/banner/{id}/up',array('as'=> 'admin.banner.up','uses' => 'BannerController@up'));

    //User
    Route::get('/admin/user/{id}/delete',array('as'=> 'admin.user.delete','uses' => 'UserController@destroy'));
    Route::resource('/admin/user', 'UserController', ['as' => 'admin']);

    Route::get('/admin/master', array('as' => 'admin.master', 'uses' => 'MasterController@getMaster'));

    //Area
    Route::get('/admin/divisi/{id}/delete',array('as'=> 'admin.divisi.delete','uses' => 'AreaController@destroy'));
    Route::resource('/admin/divisi', 'AreaController', ['as' => 'admin']);

    //Kota
    Route::get('/admin/kota/{id}/delete',array('as'=> 'admin.kota.delete','uses' => 'KotaController@destroy'));
    Route::resource('/admin/kota', 'KotaController', ['as' => 'admin']);

    //Produk
    Route::get('/admin/produk/history/all', array('as'=> 'admin.produk.historyIndex','uses' => 'ProdukController@historyIndex'));
    Route::get('/admin/produk/history/{id}', array('as'=> 'admin.produk.history','uses' => 'ProdukController@ahistory'));

    Route::get('/admin/produk/{id}/delete',array('as'=> 'admin.produk.delete','uses' => 'ProdukController@destroy'));
    Route::resource('/admin/produk', 'ProdukController', ['as' => 'admin']);

    //Distributor
    Route::get('/admin/distributor/{id}/delete',array('as'=> 'admin.distributor.delete','uses' => 'DistributorController@destroy'));
    Route::resource('/admin/distributor', 'DistributorController', ['as' => 'admin']);

    Route::post('/ajax/outlet', array('as'=> 'admin.outlet.ajax','uses' => 'OutletController@ajax'));

    //Map
    Route::get('/admin/maps/view', array('as' => 'admin.outlet.mapform','uses' => 'OutletController@formMap'));

    //Map API
    Route::get('/admin/maps', array('as' => 'admin.outlet.maps','uses' => 'OutletController@maps'));


    //Toleransi Koordinat
    Route::get('admin/outletManage', array('as' => 'admin.outletManage.index','uses' => 'OutletController@formToleransi'));
    Route::post('admin/outletManage', array('as' => 'admin.outletManage.updateToleransi','uses' => 'OutletController@updateToleransi'));
    Route::post('admin/updateTvisit', array('as' => 'admin.outletManage.updateTvisit','uses' => 'OutletController@updateTvisit'));
    Route::post('admin/updateTec', array('as' => 'admin.outletManage.updateTec','uses' => 'OutletController@updateTec'));

    //Tipe Outlet
    Route::get('/admin/tipe/{id}/delete',array('as'=> 'admin.tipe.delete','uses' => 'TipeOutletController@destroy'));
    Route::resource('/admin/tipe', 'TipeOutletController', ['as' => 'admin']);

    //Visit Plan Get data
    Route::get('admin/visitPlan', array('as' => 'admin.visitPlan.form', 'uses' => 'VisitPlanController@formVisit'));
    Route::post('admin/visitPlan', array('as' => 'admin.visitPlan.result','uses' => 'VisitPlanController@index'));

    //Visit Bukti
     Route::get('/admin/visitbukti', array('as' => 'admin.visitbukti.form','uses' =>'VisitBuktiController@formbukti'));
     Route::post('admin/visitbukti', array('as' => 'admin.visitbukti.result','uses' => 'VisitBuktiController@index'));
      Route::get('admin/download/visitbukti',array('as' => 'admin.download.visitbukti','uses' =>'DownloadController@exportVisitBukti'));
     Route::get('/admin/visitbukti/{id}/delete',array('as'=> 'admin.visitbukti.delete','uses' => 'VisitBuktiController@destroy'));

     //Billing
    //Visit Monitor Get data
    Route::get('admin/billing', array('as' => 'admin.billing.form', 'uses' => 'BillingController@formBilling'));
    Route::post('admin/billing', array('as' => 'admin.billing.result','uses' => 'BillingController@index'));
     Route::get('/admin/billing/{id}/delete',array('as'=> 'admin.billing.delete','uses' => 'BillingController@destroy'));

      //Satuan
    Route::get('/admin/satuan/{id}/delete',array('as'=> 'admin.satuan.delete','uses' => 'SatuanController@destroy'));
    Route::resource('/admin/satuan', 'SatuanController', ['as' => "admin"] );

      //brand
    Route::get('/admin/brand/{id}/delete',array('as'=> 'admin.brand.delete','uses' => 'BrandController@destroy'));
    Route::resource('/admin/brand', 'BrandController', ['as' => "admin"] );

    //Approval Checklist
    Route::get('/admin/visit/approved',array('as'=> 'admin.visit.editApprove','uses' => 'VisitPlanController@editApprove'));
    Route::post('/admin/visit/approved',array('as'=> 'admin.visit.approved','uses' => 'VisitPlanController@approvedVisit'));
    Route::get('/admin/visit/approvedHO',array('as'=> 'admin.visit.approvedHO','uses' => 'VisitPlanController@editApproveHO'));

    //Visit Monitor Get data
    Route::get('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.form', 'uses' => 'VisitMonitorController@formVisit'));
    Route::post('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.result','uses' => 'VisitMonitorController@index'));

    //Visit Plan
    Route::get('/admin/visit/{id}/delete',array('as'=> 'admin.visit.delete','uses' => 'VisitPlanController@destroy'));
    Route::resource('/admin/visit', 'VisitPlanController', ['as' => 'admin']);

    //Visiting Monitor
    Route::get('/admin/visitMonitor/{id}/delete',array('as'=> 'admin.visitMonitor.delete','uses' => 'VisitMonitorController@destroy'));
    Route::resource('/admin/visitMonitor', 'VisitMonitorController', ['as' => 'admin']);

    //Visit Problem
    Route::resource('/admin/visitProblem', 'VisitProblemController');
    Route::get('/admin/visitProblem/{id}/delete',array('as'=> 'admin.visitProblem.delete','uses' => 'VisitProblemController@destroy'));
    Route::post('admin/visitProblem',  array('as' => 'admin.visitProblem.result', 'uses'=>'VisitProblemController@index' ));
    Route::get('admin/visitProblem', array('as'=> 'admin.visitProblem.form', 'uses'=> 'VisitProblemController@form'));

    //Approval VisitProblem
    Route::get('/admin/visitProblem/approving/yet',array('as'=> 'admin.visitProblem.editApprove','uses' => 'VisitProblemController@formapproval'));
    Route::post('/admin/visitProblem/approving',array('as'=> 'admin.visitProblem.approved','uses' => 'VisitProblemController@approvedProblem'));

    //Outlet
    Route::resource('/admin/outlet', 'OutletController', [ 'as' => 'admin']);
    Route::get('/admin/outlet/{kd_outlet}/delete',array('as'=> 'admin.outlet.delete','uses' => 'OutletController@destroy'));
    // Route::get('admin/outlet', array('as' => 'admin.outlet.index', 'uses'=> 'OutletController@formOutlet'));

   

    //Sampling
    Route::resource('/admin/sampling', 'SamplingController', ['as' => 'admin']);
    Route::get('/admin/sampling/{id}/delete',array('as'=> 'admin.sampling.delete','uses' => 'SamplingController@destroy'));

laravel/app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

use App\Role;
use App\Outlet;
use App\VisitPlan;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract 
{
    //
    use Authenticatable, CanResetPassword, Notifiable;
    protected $table = 'user';
    protected $guarded = ['id'];
    protected $fillable = [
                    'kd_role',
                    'kd_kota',
                    'kd_area',
                    'nik',
                    'nama',
                    'alamat',
                    'telepon',
                    'foto',
                    'username',
                    'password',
                    'email_user',
     				'join_date',
                    'status_area',
                    'id_gcm'
                    ];

    public $timestamps = false;
    protected $effectiveMenu = null;
    protected $effectivePermission = null;
    protected $groupRole = null;

    public function setPasswordAttribute($password)
    {   
        $this->attributes['password'] = bcrypt($password);
    }

    public function roles()
    {
    	return $this->belongsTo('App\Role', 'kd_role', 'kd_role');
    }

    public function outlets()
    {
    	return $this->hasMany('App\Outlet', 'kd_user', 'id');
    }
    public function logs()
    {
        return $this->hasMany('App\Logging', 'kd_user', 'id');
    }

    public function listRole()
    {
        return $this->roles();
    }

    public function hasAccess($route)
    {
        $permissions = $this->getEffectivePermission();
        foreach ($permissions as $permission) 
        {
            if ($permission->nm_permission == $route)
            {
                return true;
            }

        }
        return false;
    }

    public function getEffectiveMenu()
    {
        if ($this->effectiveMenu != null)
        {
            return $this->effectiveMenu;
        }
        else
        {
            $role = Role::with(array('adminmenu' => function($query){
                $query->orderBy('parent_menu')->orderBy('urutan');
            }))->find($this->getRoleId());
            if ($role != null)
            {
                $effectiveMenu = array();
                foreach ($role->adminmenu as $adminmenu) 
                {
                    if ($adminmenu->parent_menu == 0 && $adminmenu->enable==1)
                    {
                        array_push($effectiveMenu, $adminmenu);
                        $adminmenu->_child = array();
                        foreach ($role->adminmenu as $child) 
                        {
                            // echo "<pre>";
                            // print_r($child->parent_menu . " - " . $adminmenu->id );
                            // echo "</pre>";
                            if ($child->parent_menu == $adminmenu->id && $child->enable==1)
                            {
                                array_push($adminmenu->_child, $child);

                                $child->_child = array();
                                foreach ($role->adminmenu as $grandChild) 
                                {
                                    if ($grandChild->parent_menu == $child->id && $grandChild->enable==1)
                                    {
                                        array_push($child->_child, $grandChild);
                                    }
                                }
                            }
                        }
                    }
                }
                $this->effectiveMenu = $effectiveMenu;
            }
            else
            {
                $this->effectiveMenu = array();
            }
            return $this->effectiveMenu;
        }
    }

    public function getEffectivePermission()
    {
        if ($this->effectivePermission != null)
        {
            return $this->effectivePermission;
        }
        else
        {
            $role = Role::with('permission')->find($this->getRoleId());
            
            if ($role != null)
            {
                $this->effectivePermission = $role->permission;
            }
            else
            {
                $this->effectivePermission = array();
            }
            return $this->effectivePermission;
        }
    }

    public function setRoleId($id)
    {
        $role = Role::find($id);
        if ($role != null)
        {
            $this->kd_role = $id;
            $this->save();
        }
    }

    public function getRoleId()
    {
        if ($this->kd_role == 0)
        {
            if ($this->roles->count() > 0)
            {
                $id = $this->roles->sortByDesc('kd_role')->first()->id;
                $this->setRoleId($id);
                return $this->kd_role;
            }
            else
            {
                return 0;
            }            
        }
        else
        {
            return $this->kd_role;
        }
    }
}

laravel/resources/views/pages/user/create.blade.php
@extends('layouts.master')

@section('link', '
    <link href="/doodle/vendors/bower_components/dropify/dist/css/dropify.min.css" rel="stylesheet" type="text/css"/>
    <link href="/doodle/vendors/bower_components/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet" type="text/css"/>
    <link href="/doodle/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css"/>')

@section('title', 'Create User')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">User management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>User Manager</span></a></li>
                            <li><a href="{{url('/admin/user')}}"><span>User</span></a></li>
                            <li class="active"><span>Add User</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-warning card-view">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Form Add User</h6>
                                    </div>
                                    @include('partials.panel')
                                    <div class="clearfix"></div>
                                </div>
                                <div id="collapse_1" class="panel-wrapper collapse in">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-wrap">

                                                    {!! Form::open(array('route' => 'admin.user.store', 'method' => 'POST','files' => true, 'data-toggle' => 'validator', 'role' => 'form')) !!}
                                                        @include('pages.user.form',array('submit' => 'Simpan'))
                                                    {!! Form::close() !!}

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

@endsection


@section('script', '
    <!-- Bootstrap Dropify JavaScript -->
    <script src="/doodle/vendors/bower_components/dropify/dist/js/dropify.min.js"></script>
    <!-- Form File Upload Data JavaScript -->
    <script src="/doodle/dist/js/form-file-upload-data.js"></script>')

laravel/resources/views/pages/user/edit.blade.php
@extends('layouts.master')

@section('link', '
    <link href="/doodle/vendors/bower_components/dropify/dist/css/dropify.min.css" rel="stylesheet" type="text/css"/>
    <link href="/doodle/vendors/bower_components/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet" type="text/css"/>
    <link href="/doodle/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css"/>')

@section('title', 'Edit User')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">User management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>User Manager</span></a></li>
                            <li><a href="{{url('/admin/user')}}"><span>User</span></a></li>
                            <li class="active"><span>Edit User</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-warning card-view">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Form Edit User</h6>
                                    </div>
                                    @include('partials.panel')
                                    <div class="clearfix"></div>
                                </div>
                                <div id="collapse_1" class="panel-wrapper collapse in">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-wrap">

                                                    {!! Form::model($data['content'],array('route' => ['admin.user.update',$data['content']->id], 'method' => 'PUT', 'files' => true, 'data-toggle' => 'validator', 'role' => 'form')) !!}
												        @include('pages.user.form-edit',array('submit' => 'Perbarui'))
												    {!! Form::close() !!}

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

@endsection


@section('script', '
    <!-- Bootstrap Daterangepicker JavaScript -->
    <script src="/doodle/vendors/bower_components/dropify/dist/js/dropify.min.js"></script>
    <!-- Form Flie Upload Data JavaScript -->
    <script src="/doodle/dist/js/form-file-upload-data.js"></script>')

laravel/resources/views/pages/user/index.blade.php
@extends('layouts.master')

@section('title', 'User List')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">User management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>User manager</span></a></li>
                            <li class="active"><span>Non SF</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-warning card-view">
                            <div class="panel-heading">
                                <div class="pull-left">
                                    <h6 class="panel-title txt-light"><i class="fa fa-user"></i>&nbsp;&nbsp;User List</h6>
                                </div>
                                @include('partials.panel')
                                <div class="clearfix"></div>
                            </div>
                            <div id="collapse_1" class="panel-wrapper collapse in">
                                <div class="panel-body">
                                    <div class="table-wrap">
                                        @if(Auth::user()->hasAccess('admin.user.create')) 
                                            <a href="{!! route('admin.user.create') !!}" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;&nbsp;Tambah User</a>
                                        @endif
                                        <br><br>
                                        <div class="table-responsive">
                                            <table id="tableuser" class="table datable_1 table-hover table-bordered display mb-30">
                                                <thead>
                                                    <tr>
                                                        <th><center>NIK</center></th>
                                                        <th><center>Nama</center></th>
                                                        <th><center>Alamat</center></th>
                                                        <th><center>Area</center></th>
                                                        <th><center>Telepon</center></th>
                                                        <th><center>Role</center></th>
                                                        @if(Auth::user()->kd_role != 3) 
                                                            <th style="min-width: 170px"><center>Action</center></th>
                                                        @endif
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($data as $row)
                                                        <tr>
                                                            <td>{{ $row->nik }}</td>
                                                            <td>{{ $row->nama }}</td>
                                                            <td>{{ $row->alamat }}</td>
                                                            <td>{{ $row->nm_area }}</td>
                                                            <td>{{ $row->telepon }}</td>
                                                            <td>{{ $row->type_role }}</td>
                                                            @if(Auth::user()->kd_role != 3)
                                                                <td> 
                                                                    <center>
                                                                        <div class="button-list">
                                                                            <a href="{!! route('admin.user.show',[$row->id]) !!}" data-toggle="tooltip" title="Detail User" class="btn btn-primary btn-sm btn-icon-anim btn-square mr-0" style="display: unset;"><i class="fa fa-search-plus" style="font-size: 14px;"></i></a>
                                                                            @if(Auth::user()->hasAccess('admin.user.edit'))
                                                                                <a href="{!! route('admin.user.edit',[$row->id]) !!}" data-toggle="tooltip" title="Edit" class="btn btn-success btn-sm btn-icon-anim btn-square mr-0" style="display: unset;"><i class="fa fa-pencil" style="font-size: 14px;"></i></a>
                                                                            @endif
                                                                            @if(Auth::user()->hasAccess('admin.user.delete'))      
                                                                                <a href="{!! route('admin.user.delete',[$row->id]) !!}" id="delete" data-toggle="tooltip" onclick="return confirm('Are you sure you want to delete this item?');" title="Delete" class="btn btn-danger btn-sm btn-icon-anim btn-square mr-0" style="display: unset;"><i class="fa fa-trash" style="font-size: 14px;"></i></a>
                                                                            @endif
                                                                        </div>
                                                                    </center>    
                                                                </td>
                                                            @endif
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
                <!-- /Row -->
            
                @include('partials.footer')
                 @section('custom-js')
     
        <script type="text/javascript">
        $(function() {
                $('#tableuser').dataTable({
                    "bPaginate": true,
                    "bLengthChange": true,
                    "bFilter": true,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
    </script>
        @endsection
            </div>
        </div>
        <!-- /Main Content -->

        @include('partials.sweetalert')

        @push('message')
            @include('partials.toastr')
        @endpush

@endsection